version: 2.1
jobs:
    build-dist:
        docker:
            - image: circleci/node:12.16
        steps:
            - checkout
            - run: npm install
            - run: npm run production
            - run:
              command: |
                if [[ ! -z $(git status --untracked-files=no --porcelain) ]]; then
                  git config user.email "ribeiro.breno@gmail.com"
                  git config user.name "Circle CI build"
                  git add .
                  git commit -m '[skip ci] Update userscript build - CircleCI'
                  git push -q
                else
                  echo "Nothing to commit!"
                fi
workflows:
    build-release:
        jobs:
            - build-dist:
                filters:
                    branches:
                        only:
                            - master
        
